### ISSUE TITLE
Growthcraft 2.1.0a

### ISSUE THREAD

**Issue by joni1** [joni1/Mod-crashes#1]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 07.05.15 02:44
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
    at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
    at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
    at growthcraft.cellar.tileentity.TileEntityFermentBarrel.getGUINetworkData(TileEntityFermentBarrel.java:381)
    at growthcraft.cellar.container.ContainerFermentBarrel.func_75137_b(ContainerFermentBarrel.java:128)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
    at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
    at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
    at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
    at growthcraft.cellar.tileentity.TileEntityFermentBarrel.getGUINetworkData(TileEntityFermentBarrel.java:381)
    at growthcraft.cellar.container.ContainerFermentBarrel.func_75137_b(ContainerFermentBarrel.java:128)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
    at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
    at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Darth_Eggedosis'/6143, l='MpServer', x=-55,47, y=69,65, z=253,55]]
    Chunk stats: MultiplayerChunkCache: 554, 554
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-52,64,252), Chunk: (at 12,4,12 in -4,15; contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 783 game time, 783 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 97 total; [EntitySheep['Sheep'/5376, l='MpServer', x=-123,50, y=74,00, z=272,50], EntitySheep['Sheep'/5377, l='MpServer', x=-125,44, y=72,00, z=282,47], EntitySheep['Sheep'/5378, l='MpServer', x=-129,66, y=77,00, z=277,50], EntitySheep['Sheep'/5379, l='MpServer', x=-126,53, y=76,00, z=279,16], EntityClientPlayerMP['Darth_Eggedosis'/6143, l='MpServer', x=-55,47, y=69,65, z=253,55], EntityZombie['Zombie'/6418, l='MpServer', x=2,50, y=31,00, z=219,50], EntityBat['Bat'/5408, l='MpServer', x=-105,91, y=16,00, z=179,97], EntityZombie['Zombie'/5409, l='MpServer', x=-108,50, y=40,00, z=184,50], EntityChicken['Chicken'/5666, l='MpServer', x=-19,50, y=63,00, z=198,50], EntityChicken['Chicken'/5667, l='MpServer', x=-21,50, y=63,00, z=198,50], EntityZombie['Zombie'/5411, l='MpServer', x=-104,88, y=41,00, z=188,25], EntityChicken['Chicken'/5668, l='MpServer', x=-31,44, y=63,00, z=188,53], EntityCreeper['Creeper'/5427, l='MpServer', x=-100,06, y=33,00, z=184,50], EntitySheep['Sheep'/5428, l='MpServer', x=-88,50, y=69,00, z=196,50], EntitySheep['Sheep'/5429, l='MpServer', x=-89,50, y=69,00, z=194,50], EntitySheep['Sheep'/5430, l='MpServer', x=-89,50, y=69,00, z=199,50], EntitySheep['Sheep'/5431, l='MpServer', x=-90,50, y=69,00, z=197,50], EntitySkeleton['Skeleton'/5691, l='MpServer', x=-25,41, y=49,00, z=300,25], EntitySkeleton['Skeleton'/5692, l='MpServer', x=-28,28, y=52,00, z=295,75], EntitySkeleton['Skeleton'/5693, l='MpServer', x=-28,31, y=49,00, z=297,31], EntitySkeleton['Skeleton'/5694, l='MpServer', x=-31,50, y=49,00, z=298,69], EntitySkeleton['Skeleton'/5695, l='MpServer', x=-29,25, y=49,00, z=297,69], EntitySkeleton['Skeleton'/5696, l='MpServer', x=-30,03, y=49,00, z=297,31], EntityZombie['Zombie'/5709, l='MpServer', x=-17,50, y=42,00, z=309,50], EntityZombie['Zombie'/5710, l='MpServer', x=-8,75, y=45,00, z=309,50], EntityCreeper['Creeper'/5711, l='MpServer', x=-28,50, y=44,00, z=313,50], EntityCreeper['Creeper'/5712, l='MpServer', x=-29,50, y=44,00, z=313,50], EntityCreeper['Creeper'/5715, l='MpServer', x=-28,38, y=45,00, z=319,50], EntitySkeleton['Skeleton'/5716, l='MpServer', x=-24,50, y=47,00, z=325,50], EntityChicken['Chicken'/5726, l='MpServer', x=-15,50, y=63,00, z=198,50], EntityZombie['Zombie'/5727, l='MpServer', x=-14,94, y=13,00, z=260,38], EntitySquid['Squid'/5728, l='MpServer', x=2,91, y=56,06, z=278,50], EntitySquid['Squid'/5729, l='MpServer', x=2,63, y=56,75, z=281,47], EntitySquid['Squid'/5730, l='MpServer', x=-1,09, y=57,34, z=283,63], EntitySkeleton['Skeleton'/5734, l='MpServer', x=-7,50, y=14,00, z=301,50], EntitySkeleton['Skeleton'/5735, l='MpServer', x=-5,50, y=11,00, z=294,06], EntitySkeleton['Skeleton'/5736, l='MpServer', x=-4,50, y=14,00, z=301,50], EntityZombie['Zombie'/5737, l='MpServer', x=-5,50, y=30,00, z=302,50], EntityZombie['Zombie'/5481, l='MpServer', x=-66,50, y=27,00, z=173,50], EntityCreeper['Creeper'/5738, l='MpServer', x=-1,50, y=30,00, z=299,50], EntityZombie['Zombie'/5740, l='MpServer', x=-4,50, y=29,00, z=315,50], EntityZombie['Zombie'/5742, l='MpServer', x=-12,78, y=42,00, z=309,75], EntityCreeper['Creeper'/5487, l='MpServer', x=-69,50, y=44,00, z=277,50], EntityZombie['Zombie'/5743, l='MpServer', x=-15,50, y=42,00, z=307,50], EntityZombie['Zombie'/5744, l='MpServer', x=-13,50, y=42,00, z=307,50], EntityCreeper['Creeper'/5773, l='MpServer', x=0,50, y=30,00, z=224,50], EntitySquid['Squid'/5776, l='MpServer', x=1,44, y=56,97, z=267,19], EntityBat['Bat'/5266, l='MpServer', x=-125,31, y=61,64, z=253,41], EntitySquid['Squid'/5780, l='MpServer', x=9,47, y=57,19, z=285,13], EntitySquid['Squid'/5781, l='MpServer', x=6,44, y=58,06, z=284,97], EntitySquid['Squid'/5783, l='MpServer', x=-1,38, y=55,19, z=280,09], EntitySquid['Squid'/5784, l='MpServer', x=7,22, y=55,06, z=275,84], EntitySquid['Squid'/5785, l='MpServer', x=7,53, y=56,31, z=281,03], EntitySquid['Squid'/5786, l='MpServer', x=7,72, y=57,16, z=271,59], EntitySquid['Squid'/5788, l='MpServer', x=3,50, y=56,78, z=283,75], EntitySquid['Squid'/5789, l='MpServer', x=5,50, y=56,91, z=282,06], EntitySpider['Spider'/5790, l='MpServer', x=2,50, y=30,73, z=290,28], EntityZombie['Zombie'/5791, l='MpServer', x=-3,12, y=31,00, z=310,70], EntitySpider['Spider'/5792, l='MpServer', x=2,28, y=28,00, z=315,72], EntityBat['Bat'/5793, l='MpServer', x=10,50, y=27,82, z=297,25], EntitySpider['Spider'/5548, l='MpServer', x=-51,75, y=30,00, z=191,03], EntityZombie['Zombie'/5549, l='MpServer', x=-57,50, y=33,00, z=181,50], EntityZombie['Zombie'/5550, l='MpServer', x=-56,50, y=33,00, z=178,50], EntitySkeleton['Skeleton'/5811, l='MpServer', x=21,06, y=12,00, z=227,53], EntityBat['Bat'/5812, l='MpServer', x=21,25, y=12,19, z=226,28], EntitySquid['Squid'/5557, l='MpServer', x=-55,53, y=58,03, z=191,22], EntityBat['Bat'/5813, l='MpServer', x=26,32, y=31,57, z=226,53], EntityBat['Bat'/5814, l='MpServer', x=27,16, y=41,82, z=226,06], EntityChicken['Chicken'/5560, l='MpServer', x=-57,38, y=63,00, z=212,41], EntityChicken['Chicken'/5561, l='MpServer', x=-56,16, y=62,61, z=205,75], EntityChicken['Chicken'/5562, l='MpServer', x=-44,44, y=64,00, z=206,53], EntityChicken['Chicken'/5563, l='MpServer', x=-53,50, y=63,00, z=208,50], EntityZombie['Zombie'/5570, l='MpServer', x=-48,34, y=46,00, z=273,95], EntityBat['Bat'/5571, l='MpServer', x=-60,41, y=39,73, z=275,47], EntityBat['Bat'/5572, l='MpServer', x=-52,25, y=43,10, z=276,41], EntityBat['Bat'/5573, l='MpServer', x=-54,25, y=39,00, z=286,47], EntityZombie['Zombie'/5576, l='MpServer', x=-55,94, y=49,00, z=287,59], EntityCreeper['Creeper'/5581, l='MpServer', x=-55,50, y=45,00, z=299,50], EntityZombie['Zombie'/5582, l='MpServer', x=-57,75, y=47,00, z=293,50], EntityZombie['Zombie'/5583, l='MpServer', x=-55,50, y=49,00, z=288,50], EntitySkeleton['Skeleton'/5328, l='MpServer', x=-132,56, y=44,00, z=172,06], EntitySheep['Sheep'/5332, l='MpServer', x=-132,50, y=71,00, z=253,63], EntitySheep['Sheep'/5333, l='MpServer', x=-130,78, y=71,00, z=252,47], EntityBat['Bat'/6363, l='MpServer', x=-65,49, y=23,90, z=208,60], EntityBat['Bat'/6365, l='MpServer', x=-45,70, y=21,21, z=199,00], EntityBat['Bat'/6367, l='MpServer', x=-67,86, y=22,82, z=214,69], EntityCow['Cow'/5609, l='MpServer', x=-44,38, y=66,00, z=176,78], EntitySkeleton['Skeleton'/5612, l='MpServer', x=-45,44, y=32,00, z=191,94], EntitySkeleton['Skeleton'/5613, l='MpServer', x=-46,09, y=32,00, z=193,16], EntitySkeleton['Skeleton'/5614, l='MpServer', x=-45,97, y=32,00, z=194,63], EntityBat['Bat'/5615, l='MpServer', x=-25,84, y=35,45, z=202,25], EntitySkeleton['Skeleton'/5626, l='MpServer', x=-30,31, y=49,00, z=298,13], EntityItem['item.tile.gravel'/5371, l='MpServer', x=-117,63, y=48,13, z=190,41], EntityItem['item.tile.gravel'/5372, l='MpServer', x=-112,28, y=48,13, z=189,19], EntityCreeper['Creeper'/5373, l='MpServer', x=-119,53, y=61,00, z=228,00], EntityCreeper['Creeper'/5374, l='MpServer', x=-120,50, y=61,00, z=227,31], EntityCreeper['Creeper'/5375, l='MpServer', x=-121,38, y=61,00, z=227,97]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2688159768 bytes (2563 MB) / 4160749568 bytes (3968 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:PermSize=128M -XX:MaxPermSize=512M -Xms3072M -Xmx6144M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.113.1381 Minecraft Forge 10.13.3.1381 12 mods loaded, 12 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.10.113.1381} [Forge Mod Loader](forge-1.7.10-10.13.3.1381-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.13.3.1381} [Minecraft Forge](forge-1.7.10-10.13.3.1381-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft|Bees{2.1.0} [Growthcraft Bees](growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.3.1381-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6900 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

The game crashes when I try to open anything from Growthcraft Cellar

**Comment by clouths** [comment]
This bug is due to a fluid fix in Minecraft Forge.
When you are under 10.13.2.1291 or less, this bug doesn't happen but with Forge 10.3.3.XXXX + (fluid update), it happens.
It only means that Growthcraft does not support Minecraft Forge fluid update yet.

**Comment by joni1** [comment]
ah, thanks man, just have to get rid of growthcraft cellar then
